baseURL: "https://book.kubetencent.io"
languageCode: zh
defaultContentLanguage: zh
title: "腾讯云容器服务"
theme: "hugo-theme-learn"
metaDataFormat: "yaml"
defaultContentLanguageInSubdir: false

markup:
  tableOfContents:
    endLevel: 6

params:
  description: "腾讯云容器服务"
  author: "腾讯云容器架构师团队"
  showVisitedLinks: true
  disableBreadcrumb: false
  disableNextPrev: false
  ordersectionsby: weight
  cdn:
    enable: true
    css: "https://kubetencent-1251707795.cos.accelerate.myqcloud.com/css/bundle.min.b0e6163350b1169d986890f4bd317db6286105863b7a53274abdb5c8d935eaa1.css"
    js: "https://kubetencent-1251707795.cos.accelerate.myqcloud.com/js/bundle.min.8d534562810f42a5942ec72a0b7ae599c8bf0c96a4c8d6fafffa9bf21fce9d77.js"
  logo:
    text: "腾讯云容器服务指南"
    image: "https://res.cloudinary.com/imroc/image/upload/c_scale,w_64/v1583293443/kubernetes-practice-guide/img/kubernetes.png"
  gitcomment:
    owner: "TencentCloudContainerTeam"
    repo: "book"
    admin: ["imroc", "coderwangke", "Willbern"]
    clientId: "4e9444088ec088b58f37"
    clientSecret: "b8faa4be9753a13d0b01ccdf4ccc015f9983b58c"
  algolia:
    index: "kubetencent-book-zh"
    key: "5b4678e9995fe4211c4fa43ad2ffdab5"
    appID: "B6Q6PSGUV5"
  github:
    repo: "TencentCloudContainerTeam/book"

outputs:
  home: [ "HTML", "RSS", "JSON"]

languages:
  zh:
    editURL: "https://github.com/TencentCloudContainerTeam/book/edit/master/content/zh/"
    weight: 1
    contentDir: content/zh
    languageName: 简体中文
    dateFormat: "2006-01-02"
    menu:
    - shortcuts:
        name: "<i class='fab fa-fw fa-github'></i> GitHub 仓库"
        identifier: "ds"
        url: "https://github.com/TencentCloudContainerTeam/book"
        weight: 10
  en:
    weight: 2
    contentDir: content/en
    languageName: English
    menu:
    - shortcuts:
        name: "<i class='fab fa-fw fa-github'></i> GitHub Repo"
        identifier: "ds"
        url: "https://github.com/TencentCloudContainerTeam/book"
        weight: 10